Update upstream_sync_fork.yml

diff --git a/.github/workflows/upstream_sync_fork.yml b/.github/workflows/upstream_sync_fork.yml
--- a/.github/workflows/upstream_sync_fork.yml
+++ b/.github/workflows/upstream_sync_fork.yml
@@ -16,26 +16,38 @@ jobs:
     if: ${{ github.event.repository.fork }}
 
     steps:
-      # Step 1: run a standard checkout action
+      # Step 1: checkout target repo
       - name: Checkout target repo
         uses: actions/checkout@v6
 
-      # Step 2: run the sync action
+      # Step 2: check token
+      - name: Check sync token
+        run: |
+          if [ -z "${{ secrets.UPDATESTREAM_SYNC_TOKEN }}" ]; then
+            echo "UPDATESTREAM_SYNC_TOKEN is empty"
+            exit 1
+          else
+            echo "UPDATESTREAM_SYNC_TOKEN exists"
+          fi
+
+      # Step 3: sync upstream changes
       - name: Sync upstream changes
         id: sync
         uses: aormsby/fork-sync-with-upstream-action@v3.4.3
+        env:
+          GH_TOKEN: ${{ secrets.UPDATESTREAM_SYNC_TOKEN }}
         with:
           upstream_sync_repo: fe-spark/EcoHub
           upstream_sync_branch: main
           target_sync_branch: main
-          target_repo_token: ${{ secrets.UPDATESTREAM_SYNC_TOKEN }} # automatically generated, no need to set
+          target_repo_token: ${{ secrets.UPDATESTREAM_SYNC_TOKEN }}
 
-          # Set test_mode true to run tests instead of the true action!!
           test_mode: false
 
+      # Step 4: sync check
       - name: Sync check
         if: failure()
         run: |
-          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，详细教程请查看项目README.md "
-          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the project README.md for instructions. "
+          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新"
+          echo "[Error] Due to a change in the workflow file of the upstream repository"
           exit 1
